language: ruby
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
services:
  - postgresql
addons:
  postgresql: '9.4'
before_install:
  - gem update --system
  - gem update bundler
  - nvm install
install: bundle install --deployment --path vendor/bundle && yarn install
env:
  - OAS_PATH="_open_api/api_specs"
before_script:
  - |
    if [ -z "$SSH_KEY_REQUIRED" ]; then
      echo "Skipping setting up SSH Key";
    else
      echo "Setting up SSH key";
      declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"
      openssl aes-256-cbc -K $encrypted_293bfe86302a_key -iv $encrypted_293bfe86302a_iv -in "github_deploy_key.enc" -out "$SSH_FILE" -d
      chmod 600 "$SSH_FILE" \
        && printf "%s\n" \
             "Host github.com" \
             "  IdentityFile $SSH_FILE" \
             "  LogLevel ERROR" >> ~/.ssh/config
    fi
  - RAILS_ENV=test bundle exec rake db:create db:migrate
script:
  - bundle exec rake spec
  - bundle exec rubocop
  - bundle exec rake ci:verify_pages
  - bundle exec rake ci:verify_navigation
  - bundle exec rake ci:verify_oas_reference
  - bundle exec rake ci:verify_error_urls_resolve
  - bundle exec rake ci:check_word_blocklist
  - RAILS_ENV=test bundle exec rake webpacker:compile
  - ./node_modules/.bin/mdspell -r -n -a --en-us '_documentation/**/*.md' '_partials/*.md' '_partials/**/*.md' '_modals/**/*.md' '_tutorials/**.md'
  - yarn test
