version: '3'
services:
  db:
    image: postgres
  web:
    image: nexmodeveloper_app
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - clean
      - update
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USERNAME=postgres
      - RAILS_ENV=development
      - RACK_ENV=development
  clean:
    image: nexmodeveloper_app
    build: .
    command: bash -c "rm -Rf public/packs && rm -f /app/tmp/pids/server.pid"
    volumes:
      - .:/app
  update:
    image: nexmodeveloper_app
    build: .
    command: bash -c "rake db:setup"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USERNAME=postgres
