---
title: Add two factor authentication to a Microsoft bot with Nexmoâ€™s Verify API
external_link: https://www.nexmo.com/blog/2018/07/11/add-two-factor-authentication-to-a-microsoft-bot-with-nexmos-verify-api-dr/
image_url: https://www.nexmo.com/wp-content/uploads/2018/07/2FA-MS-BOT-600x300.png
description: Detailed tutorial on adding two factor authentication to a Microsoft chat bot using Nexmo's Verify API and .NET.
products:
  - verify
languages:
 - dotnet
---

