title: Sending a Facebook message with failover
description: The Dispatch API provides the ability to create message workflows with failover to secondary channels. This task looks at using the Dispatch API to send a Facebook message with failover to the SMS channel.
products:
  - dispatch

introduction: 
  title: Introduction to this task
  description: This task shows you how to use the failover functionality of the Dispatch API.
  content: |
    # Introduction
    The Dispatch API features workflows with automatic failover. In this task you see how to send a Facebook Messenger message with automatic failover to SMS.

    > **NOTE:** This task assumes you have already created a Facebook Profile and a Facebook Page.

prerequisites:
- create-nexmo-account
- install-nodejs
- install-nexmo-cli-beta
- install-node-sdk-beta
- olympus/configure-webhooks
- olympus/write-webhook-server
- olympus/test-webhook-server

tasks:
- olympus/create-application
- olympus/link-facebook-page
- olympus/link-application-to-facebook
- olympus/send-facebook-failover

conclusion:
  title: What's next?
  description: What else can you do with the Dispatch API?
  content: |

    # What's next?
    You can do a lot more with the Dispatch API.

    See [Dispatch API documentation](/dispatch/overview) and [a multi-user, multi-channel workflow Dispatch use case](/tutorials/dispatch-user-fallback).
