navigation_weight:
  Application: 0
  Messaging: 1
  SMS: 1
  Voice: 2
  Verify: 3
  Number Insight: 4
  Messages: 5
  Dispatch: 6
  Numbers: 98
  Account: 99
  Vonage Business Cloud: 7

  Number Programmability: 1
  VBC APIs: 2
  Getting Started: 1
  Account API: 2
  Extension API: 3
  User API: 4
  Vonage Integration Suite: 3

  Onboarding: 0
  Overview: 1
  Developer Preview: 2
  Tasks: 3
  Quickstarts: 3
  Guides: 4
  Code Snippets: 5

  Tutorials: 6
  Troubleshooting: 7
  API Reference: 7
  Conversation: 8

  Voice API: 1
  SIP: 2

  Client SDK: 30
  NCCO Reference: 40
  SDK Documentation: 40
  API Reference: 50

  Overview: 1
  Concepts: 2
  In-App Messaging: 4
  In-App Voice: 3
  In-App Video: 5

  Messages API: 1
  Dispatch API: 2

  Secret Management: 30

navigation_overrides:
  application:
    svg: 'flow'
    svgColor: 'indigo'
  concepts:
    navigation_weight: 0
    svg: 'mind-map'
    svgColor: 'red'
  messaging:
    svg: 'message'
    svgColor: 'purple'
    sms:
      collapsible: true
    conversion-api:
      collapsible: true
    us-short-codes:
      collapsible: true
  voice:
    svg: 'phone'
    svgColor: 'green'
    voice-api:
      collapsible: true
      guides:
        lex-connector:
          label: 'Dev Preview'
        websockets:
          label: 'Beta'
    sip:
      collapsible: true
  verify:
    svg: 'lock'
    svgColor: 'indigo'
  number-insight:
    svg: 'file-search'
    svgColor: 'orange'
  account:
    svg: 'user'
    svgColor: 'blue'
    secret-management:
      collapsible: true
  redact:
    label: 'Dev Preview'
    svg: 'lock'
    svgColor: 'red'
  client-sdk:
    svg: 'queue'
    svgColor: 'teal'
    label: 'Dev Preview'
    sdk-documentation:
      link: false
    setup:
      collapsible: true
    in-app-voice:
      collapsible: true
    in-app-messaging:
      collapsible: true
  numbers:
    svg: 'phone-number'
    svgColor: 'red'
  audit:
    svg: 'file-search'
    svgColor: 'green'
    label: 'Beta'
  messages:
    svg: 'chat'
    svgColor: 'purple'
    label: 'Beta'
    code-snippets:
      collapsible: false
      sms:
        collapsible: true
      mms:
        collapsible: true
      messenger:
        collapsible: true
      viber:
        collapsible: true
      whatsapp:
        collapsible: true
  dispatch:
    svg: 'flow'
    svgColor: 'purple'
    label: 'Beta'
  conversation:
    svg: 'message'
    svgColor: 'teal'
    label: 'Dev Preview'
  vonage-business-cloud:
    svg: 'telephone'
    svgColor: 'green'
  contribute:
    administration:
      navigation_weight: 9999
