products:
  - account
  - account/subaccounts
  - application
  - audit
  - client-sdk
  - client-sdk/in-app-voice
  - client-sdk/in-app-video
  - client-sdk/in-app-messaging
  - concepts
  - conversation
  - dispatch
  - messages
  - messaging
  - messaging/sms
  - messaging/conversion-api
  - messaging/us-short-codes
  - number-insight
  - numbers
  - redact
  - reports
  - tools
  - verify
  - voice
  - voice/sip
  - voice/voice-api
  - vonage-business-cloud
  - vonage-business-cloud/smart-numbers
  - vonage-business-cloud/integration-suite
  - vonage-business-cloud/vbc-apis/account-api
  - vonage-business-cloud/vbc-apis/extension-api
  - vonage-business-cloud/vbc-apis/reports-api
  - vonage-business-cloud/vbc-apis/user-api
