---
"/contribute": "/contribute/overview"
"/styleguide": "/contribute/guides/markdown-guide"
"/write-the-docs": "/contribute/guides/writing-style-guide"
"/account": "/account/secret-management/overview"
"/account/overview": "/account/secret-management/overview"
"/account/building-blocks": "/account/secret-management/building-blocks/create-a-secret"
"/account/building-blocks/buy-a-number": "/numbers/building-blocks/buy-a-number"
"/account/guides": "/numbers/guides"
"/account/guides/management": "/numbers/guides/management"
"/account/guides/numbers": "/numbers/guides/numbers"
"/account/guides/payments": "/numbers/guides/payments"
"/account/numbers/overview": "/numbers/overview"
"/account/numbers/guides": "/numbers/guides"
"/account/numbers/guides/numbers": "/numbers/guides/numbers"
"/account/numbers/guides/management": "/numbers/guides/management"
"/account/numbers/guides/payments": "/numbers/guides/payments"
"/account/numbers/building-blocks": "/numbers/building-blocks"
"/account/numbers/building-blocks/buy-a-number": "/numbers/building-blocks/buy-a-number"
"/account/secret-management/api-reference": "/api/account/secret-management"
"/account/api-reference": "/api/account"
"/api/voice/ncco": "/voice/voice-api/ncco-reference"
"/api/developer": "/api/developer/account"
"/api/account": "/api/developer/account"
"/api/messages": "/api/developer/account"
"/api/numbers": "/api/developer/account"
"/audit/api-reference": "/api/audit"
"/contribute/guides/styleguide": "/contribute/guides/markdown-guide"
"/contribute/guides/write-the-docs": "/contribute/guides/writing-style-guide"
"/events": "/community"
"/messaging": "/messaging/sms/overview"
"/messaging/sms": "/messaging/sms/overview"
"/messaging/us-short-codes": "/messaging/us-short-codes/overview"
"/messaging/us-short-codes/guides": "/messaging/us-short-codes/guides/campaign-subscription-management"
"/messaging/conversion-api": "/messaging/conversion-api/overview"
"/messaging/sns": "/messaging/sns/overview"
"/messaging/sms/building-blocks": "/messaging/sms/building-blocks/send-an-sms"
"/messaging/sms/building-blocks/receive-a-delivery-receipt": "/messaging/sms/guides/delivery-receipts"
"/messaging/sms/guides": "/messaging/sms/overview#sms-api-features"
"/messaging/sms/guides/concatenation": "/messaging/sms/guides/concatenation-and-encoding"
"/messaging/sms/api-reference": "/api/sms"
"/messaging/tutorials": "/messaging/sms/tutorials"
"/messaging/sms/guides/global-messaging": "/messaging/sms/guides/country-specific-features"
"/messaging/sms/guides/delivery-reciepts": "/messaging/sms/guides/delivery-receipts"
"/messages-and-workflows-apis/messages/api-reference": "/api/messages-and-workflows-apis/messages"
"/messages-and-workflows-apis/workflows/api-reference": "/api/messages-and-workflows-apis/workflows"
"/messages-and-workflows-apis/messages/guides": "/messages-and-workflows-apis/messages/guides/facebook-messenger"
"/messages-and-workflows-apis/workflows/guides": "/messages-and-workflows-apis/workflows/guides/failover"
"/messages-and-workflows-apis/messages/building-blocks": "/messages-and-workflows-apis/messages/building-blocks/send-an-sms-with-messages-api"
"/messages-and-workflows-apis/workflows/building-blocks": "/messages-and-workflows-apis/workflows/building-blocks/send-a-message-with-failover"
"/messages-and-workflows-apis/workflows/building-blocks/send-a-message-with-failover": "/messages-and-workflows-apis/workflows/building-blocks/send-a-facebook-message-with-failover"
"/number-insight": "/number-insight/overview"
"/number-insight/guides": "/number-insight/guides/cnam"
"/number-insight/building-blocks": "/number-insight/building-blocks/number-insight-basic"
"/number-insight/api-reference": "/api/number-insight"
"/numbers/guides": "/numbers/guides/numbers"
"/numbers/building-blocks": "/numbers/building-blocks/number-management/buy-a-number"
"/redact": "/redact/overview"
"/redact/api-reference": "/api/redact"
"/sip": "/voice/sip"
"/slack": "/community/slack"
"/sms": "/messaging/sms/overview"
"/sms/building-blocks": "/messaging/sms/building-blocks/send-an-sms"
"/sms/guides": "/messaging/sms/guides/us-short-codes/overview"
"/tools/cli": "/tools"
"/tutorials/call-whisper-with-on-answer": "/tutorials/add-a-call-whisper-to-an-inbound-call"
"/verify": "/verify/overview"
"/verify/api-reference": "/api/verify"
"/verify/guides": "/verify/guides/verify-a-user"
"/verify/tutorial": "/verify/tutorials/passwordless-authentication"
"/verify/building-blocks": "/verify/building-blocks/send-verify-request"
"/voice": "/voice/overview"
"/voice/api-reference": "/voice/voice-api/api-reference"
"/voice/sip": "/voice/sip/overview"
"/voice/overview": "/voice/voice-api/overview"
"/voice/tutorials": "/voice/voice-api/tutorials"
"/voice/building-blocks": "/voice/voice-api/building-blocks/before-you-begin"
"/voice/voice-api/building-blocks": "/voice/voice-api/building-blocks/before-you-begin"
"/voice/building-blocks/connect-a-phone-call": "/voice/voice-api/building-blocks/connect-an-inbound-call"
"/voice/building-blocks/receive-a-phone-call": "/voice/voice-api/building-blocks/receive-an-inbound-call"
"/voice/voice-api/building-blocks/connect-a-phone-call": "/voice/voice-api/building-blocks/connect-an-inbound-call"
"/voice/voice-api/building-blocks/make-a-phone-call": "/voice/voice-api/building-blocks/make-an-outbound-call"
"/voice/voice-api/building-blocks/receive-a-phone-call": "/voice/voice-api/building-blocks/receive-an-inbound-call"
"/voice/guides": "/voice/voice-api/guides/call-flow"
"/voice/guides/sip": "/voice/sip"
"/voice/guides/voice-app-components": "/voice/voice-api/guides/voice-app-components"
"/voice/guides/connect-two-users": "/voice/voice-api/guides/connect-two-users"
"/voice/guides/connecting-voice-calls-to-amazon-lex-bots": "/voice/voice-api/guides/connecting-voice-calls-to-amazon-lex-bots"
"/voice/guides/create-conferences": "/voice/voice-api/guides/create-conferences"
"/voice/guides/handle-call-status": "/voice/voice-api/guides/handle-call-status"
"/voice/guides/inbound-calls": "/voice/voice-api/guides/inbound-calls"
"/voice/guides/interactive-voice-response": "/voice/voice-api/guides/interactive-voice-response"
"/voice/guides/ncco": "/voice/voice-api/guides/ncco"
"/voice/guides/outbound-calls": "/voice/voice-api/guides/outbound-calls"
"/voice/guides/record-calls-and-conversations": "/voice/voice-api/guides/record-calls-and-conversations"
"/voice/guides/call-a-websocket": "/voice/voice-api/guides/call-a-websocket"
"/voice/guides/ncco-reference": "/voice/voice-api/ncco-reference"
"/voice/voice-api/websockets": "/voice/voice-api/guides/websockets"
"/voice/voice-api/api-reference": "/api/voice"
"/voice/voice-api/guides/outbound-calls": "/voice/voice-api/building-blocks/make-an-outbound-call"
"/voice/voice-api/guides/record-calls-and-conversations": "/voice/voice-api/guides/recording"
"/voice/voice-api/guides/connect-two-users": "/voice/voice-api/building-blocks/connect-an-inbound-call"
"/voice/voice-api/guides/create-conferences": "/voice/voice-api/building-blocks/connect-callers-into-a-conference"
"/voice/voice-api/guides/call-a-websocket": "/voice/voice-api/guides/websockets"
"/voice/voice-api/guides/handle-call-status": "/voice/voice-api/guides/call-flow"
"/voice/voice-api/guides/interactive-voice-response": "/voice/voice-api/building-blocks/handle-user-input-with-dtmf"
"/voice/voice-api/guides/inbound-calls": "/voice/voice-api/building-blocks/connect-an-inbound-call"
"/voice/voice-api/guides/voice-app-components": "/voice/voice-api/guides/legs-conversations"
"/voice/voice-api/guides/ssml": "/voice/voice-api/guides/text-to-speech#ssml"
"/voice/voice-api/guides/connecting-voice-calls-to-amazon-lex-bots": "/voice/voice-api/guides/lex-connector"
