---
"/messages/external-accounts/api-reference": "/api/external-accounts"
"/dispatch/external-accounts/api-reference": "/api/external-accounts"
"/contribute": "/contribute/overview"
"/styleguide": "/contribute/guides/markdown-guide"
"/write-the-docs": "/contribute/guides/writing-style-guide"
"/account": "/account/overview"
"/account/code-snippets": "/account/code-snippets/create-a-secret"
"/account/code-snippets/buy-a-number": "/numbers/code-snippets/buy-a-number"
"/account/guides": "/account/guides/dashboard-management"
"/account/guides/management": "/account/guides/dashboard-management"
"/account/guides/numbers": "/numbers/guides/numbers"
"/account/guides/payments": "/numbers/guides/payments"
"/account/numbers/overview": "/numbers/overview"
"/account/numbers/guides": "/numbers/guides"
"/account/numbers/guides/numbers": "/numbers/guides/numbers"
"/account/numbers/guides/management": "/numbers/guides/management"
"/account/numbers/guides/payments": "/numbers/guides/payments"
"/account/numbers/code-snippets": "/numbers/code-snippets"
"/account/numbers/code-snippets/buy-a-number": "/numbers/code-snippets/buy-a-number"
"/account/secret-management/api-reference": "/api/account"
"/account/api-reference": "/api/account"
"/application/api-reference": "/api/application.v2"
"/voice/voice-api": "/voice/voice-api/overview"
"/audit/api-reference": "/api/audit"
"/concepts": "/concepts/overview"
"/concepts/guides/applications": "/application/overview"
"/contribute/guides/styleguide": "/contribute/guides/markdown-guide"
"/contribute/guides/write-the-docs": "/contribute/guides/writing-style-guide"
"/dispatch/api-reference": "/api/dispatch"
"/dispatch/concepts": "/dispatch/concepts/workflows"
"/dispatch/code-snippets": "/dispatch/code-snippets/before-you-begin"
"/events": "/community"
"/extend/microsft-flow": "/extend/microsoft-flow"
"/messaging": "/messaging/sms/overview"
"/messaging/sms": "/messaging/sms/overview"
"/messaging/us-short-codes": "/messaging/us-short-codes/overview"
"/messaging/us-short-codes/guides": "/messaging/us-short-codes/guides/campaign-subscription-management"
"/messaging/conversion-api": "/messaging/conversion-api/overview"
"/messaging/sms/code-snippets": "/messaging/sms/code-snippets/send-an-sms"
"/messaging/sms/code-snippets/receive-a-delivery-receipt": "/messaging/sms/guides/delivery-receipts"
"/messaging/sms/guides": "/messaging/sms/overview#sms-api-features"
"/messaging/sms/guides/concatenation": "/messaging/sms/guides/concatenation-and-encoding"
"/messaging/sms/api-reference": "/api/sms"
"/messaging/tutorials": "/messaging/sms/tutorials"
"/messaging/sms/guides/global-messaging": "/messaging/sms/guides/country-specific-features"
"/messaging/sms/guides/delivery-reciepts": "/messaging/sms/guides/delivery-receipts"
"/messages-and-workflows-apis": "/messages/overview"
"/messages-and-workflows-apis/messages": "/messages/overview"
"/messages-and-workflows-apis/workflows": "/dispatch/overview"
"/messages-and-workflows-apis/messages/overview": "/messages/overview"
"/messages-and-workflows-apis/workflows/overview": "/dispatch/overview"
"/messages-and-workflows-apis/messages/api-reference": "/api/messages-olympus"
"/messages-and-workflows-apis/messages/guides": "/messages/code-snippets/client-library"
"/messages-and-workflows-apis/messages/code-snippets": "/messages/code-snippets/send-an-sms-with-messages-api"
"/messages-and-workflows-apis/messages/guides/sms-messages": "/tutorials/sending-sms-messages-with-messages-api"
"/messages-and-workflows-apis/messages/guides/facebook-messenger": "/tutorials/sending-facebook-messenger-messages-with-messages-api"
"/messages-and-workflows-apis/messages/guides/viber-service-messages": "/tutorials/sending-viber-service-messages-with-messages-api"
"/messages-and-workflows-apis/messages/guides/whatsapp": "/tutorials/sending-whatsapp-messages-with-messages-api"
"/messages-and-workflows-apis/workflows/api-reference": "/api/dispatch"
"/messages-and-workflows-apis/workflows/guides": "/dispatch/code-snippets/client-library"
"/messages-and-workflows-apis/workflows/code-snippets": "/dispatch/code-snippets/send-a-message-with-failover"
"/messages-and-workflows-apis/workflows/code-snippets/send-a-message-with-failover": "/dispatch/code-snippets/send-a-facebook-message-with-failover"
"/messages-and-workflows-apis/workflows/guides/failover": "/tutorials/sending-facebook-message-with-failover"
"/messages-and-workflows-apis/messages/code-snippets/send-an-sms-with-messages-api": "/messages/code-snippets/send-an-sms-with-messages-api"
"/messages-and-workflows-apis/messages/code-snippets/send-a-viber-service-message": "/messages/code-snippets/send-a-viber-service-message"
"/messages-and-workflows-apis/messages/code-snippets/send-with-facebook-messenger": "/messages/code-snippets/send-with-facebook-messenger"
"/messages/api-reference": "/api/messages-olympus"
"/messages/code-snippets": "/messages/code-snippets/before-you-begin"
"/messages/concepts": "/messages/concepts/facebook"
"/messages/code-snippets/send-mms-basic-auth": "/messages/code-snippets/send-mms"
"/messages/code-snippets/send-whatsapp-template": "/messages/code-snippets/whatsapp/send-mtm"
"/messages/code-snippets/send-a-whatsapp-message": "/messages/code-snippets/whatsapp/send-text"
"/messages/code-snippets/send-whatsapp-image": "/messages/code-snippets/whatsapp/send-image"
"/messages/code-snippets/send-whatsapp-audio": "/messages/code-snippets/whatsapp/send-audio"
"/messages/code-snippets/send-whatsapp-file": "/messages/code-snippets/whatsapp/send-file"
"/messages/code-snippets/send-with-facebook-messenger": "/messages/code-snippets/messenger/send-text"
"/messages/code-snippets/send-an-sms-with-messages-api": "/messages/code-snippets/sms/send-sms"
"/messages/code-snippets/send-mms": "/messages/code-snippets/mms/send-mms"
"/messages/code-snippets/send-a-viber-service-message": "/messages/code-snippets/viber/send-text"
"/number-insight": "/number-insight/overview"
"/number-insight/guides": "/number-insight/guides/cnam"
"/number-insight/code-snippets": "/number-insight/code-snippets/number-insight-basic"
"/number-insight/api-reference": "/api/number-insight"
"/numbers": "/numbers/overview"
"/numbers/api-reference": "/api/numbers"
"/numbers/guides": "/numbers/guides/number-management"
"/numbers/guides/numbers": "/numbers/guides/number-management"
"/numbers/guides/management": "/numbers/guides/number-management"
"/numbers/code-snippets": "/numbers/code-snippets/buy-a-number"
"/redact": "/redact/overview"
"/redact/api-reference": "/api/redact"
"/sip": "/voice/sip"
"/slack": "/community/slack"
"/sms": "/messaging/sms/overview"
"/sms/code-snippets": "/messaging/sms/code-snippets/send-an-sms"
"/sms/guides": "/messaging/sms/guides/us-short-codes/overview"
"/tools/cli": "/tools"
"/tutorials/call-whisper-with-on-answer": "/tutorials/add-a-call-whisper-to-an-inbound-call"
"/tutorials/smart-local-numbers": "/tutorials/local-numbers"
"/verify": "/verify/overview"
"/verify/api-reference": "/api/verify"
"/verify/guides": "/verify/guides/workflows-and-events"
"/verify/guides/verification-events": "/verify/guides/workflows-and-events"
"/verify/tutorial": "/verify/tutorials/passwordless-authentication"
"/verify/code-snippets": "/verify/code-snippets/send-verify-request"
"/voice": "/voice/overview"
"/voice/api-reference": "/voice/voice-api/api-reference"
"/voice/sip": "/voice/sip/overview"
"/voice/overview": "/voice/voice-api/overview"
"/voice/tutorials": "/voice/voice-api/tutorials"
"/voice/code-snippets": "/voice/voice-api/code-snippets/before-you-begin"
"/voice/voice-api/code-snippets": "/voice/voice-api/code-snippets/before-you-begin"
"/voice/code-snippets/connect-a-phone-call": "/voice/voice-api/code-snippets/connect-an-inbound-call"
"/voice/code-snippets/receive-a-phone-call": "/voice/voice-api/code-snippets/receive-an-inbound-call"
"/voice/voice-api/code-snippets/connect-a-phone-call": "/voice/voice-api/code-snippets/connect-an-inbound-call"
"/voice/voice-api/code-snippets/make-a-phone-call": "/voice/voice-api/code-snippets/make-an-outbound-call"
"/voice/voice-api/code-snippets/receive-a-phone-call": "/voice/voice-api/code-snippets/receive-an-inbound-call"
"/voice/guides": "/voice/voice-api/guides/call-flow"
"/voice/guides/sip": "/voice/sip"
"/voice/guides/voice-app-components": "/voice/voice-api/guides/voice-app-components"
"/voice/guides/connect-two-users": "/voice/voice-api/guides/connect-two-users"
"/voice/guides/connecting-voice-calls-to-amazon-lex-bots": "/voice/voice-api/guides/connecting-voice-calls-to-amazon-lex-bots"
"/voice/guides/create-conferences": "/voice/voice-api/guides/create-conferences"
"/voice/guides/handle-call-status": "/voice/voice-api/guides/handle-call-status"
"/voice/guides/inbound-calls": "/voice/voice-api/guides/inbound-calls"
"/voice/guides/interactive-voice-response": "/voice/voice-api/guides/interactive-voice-response"
"/voice/guides/ncco": "/voice/voice-api/guides/ncco"
"/voice/guides/outbound-calls": "/voice/voice-api/guides/outbound-calls"
"/voice/guides/record-calls-and-conversations": "/voice/voice-api/guides/record-calls-and-conversations"
"/voice/guides/call-a-websocket": "/voice/voice-api/guides/call-a-websocket"
"/voice/guides/ncco-reference": "/voice/voice-api/ncco-reference"
"/voice/voice-api/websockets": "/voice/voice-api/guides/websockets"
"/voice/voice-api/api-reference": "/api/voice"
"/voice/voice-api/guides/outbound-calls": "/voice/voice-api/code-snippets/make-an-outbound-call"
"/voice/voice-api/guides/record-calls-and-conversations": "/voice/voice-api/guides/recording"
"/voice/voice-api/guides/connect-two-users": "/voice/voice-api/code-snippets/connect-an-inbound-call"
"/voice/voice-api/guides/create-conferences": "/voice/voice-api/code-snippets/connect-callers-into-a-conference"
"/voice/voice-api/guides/call-a-websocket": "/voice/voice-api/guides/websockets"
"/voice/voice-api/guides/handle-call-status": "/voice/voice-api/guides/call-flow"
"/voice/voice-api/guides/interactive-voice-response": "/voice/voice-api/code-snippets/handle-user-input-with-dtmf"
"/voice/voice-api/guides/inbound-calls": "/voice/voice-api/code-snippets/connect-an-inbound-call"
"/voice/voice-api/guides/voice-app-components": "/voice/voice-api/guides/legs-conversations"
"/voice/voice-api/guides/ssml": "/voice/voice-api/guides/customizing-tts"
"/voice/voice-api/guides/connecting-voice-calls-to-amazon-lex-bots": "/voice/voice-api/guides/lex-connector"
"/vonage-business-cloud/vbc-apis/account-api/api-reference": "/api/vonage-business-cloud/account"
"/vonage-business-cloud/vbc-apis/extension-api/api-reference": "/api/vonage-business-cloud/extension"
"/vonage-business-cloud/vbc-apis/user-api/api-reference": "/api/vonage-business-cloud/user"
"/vonage-business-cloud/integration-suite/api-reference": "/api/vonage-business-cloud/vgis"
"/vonage-business-cloud/number-programmability/overview": "/vonage-business-cloud/smart-numbers/overview"
"/vonage-business-cloud/number-programmability/guides/register": "/vonage-business-cloud/smart-numbers/guides/enable-addon"
"/vonage-business-cloud/number-programmability/guides/billing": "/vonage-business-cloud/smart-numbers/guides/billing"
"/vonage-business-cloud/number-programmability/guides/provision-nps": "/vonage-business-cloud/smart-numbers/guides/provision-smart-numbers"
"/vonage-business-cloud/number-programmability/guides/create-voice-application": "/vonage-business-cloud/smart-numbers/guides/create-voice-application"
"/vonage-business-cloud/number-programmability/guides/vbc-resources": "/vonage-business-cloud/smart-numbers/guides/vbc-resources"
"/vonage-business-cloud/number-programmability/code-snippets/vbc-receive-inbound-call": "/vonage-business-cloud/smart-numbers/code-snippets/vbc-receive-inbound-call"
"/vonage-business-cloud/number-programmability/code-snippets/vbc-route-to-extension": "/vonage-business-cloud/smart-numbers/code-snippets/vbc-route-to-extension"
"/tutorials/client-sdk-ios-make-receive-calls-swift": "https://developer.nexmo.com/client-sdk/in-app-voice/guides/start-and-receive-calls/ios"
"/tutorials/client-sdk-android-make-receive-calls": "/client-sdk/in-app-voice/guides/start-and-receive-calls/android"
"/account/subaccounts/api-reference": "/api/subaccounts"
"/account/subaccounts/tutorials": "/subaccounts/tutorials"
