---
"/contribute": "/contribute/overview"
"/styleguide": "/contribute/guides/markdown-guide"
"/write-the-docs": "/contribute/guides/writing-style-guide"
"/account": "/account/overview"
"/account/guides": "/account/guides/management"
"/account/building-blocks": "/account/building-blocks/buy-a-number"
"/api/voice/ncco": "/voice/voice-api/ncco-reference"
"/api/developer": "/api/developer/account"
"/api/account": "/api/developer/account"
"/api/messages": "/api/developer/account"
"/api/numbers": "/api/developer/account"
"/contribute/guides/styleguide": "/contribute/guides/markdown-guide"
"/contribute/guides/write-the-docs": "/contribute/guides/writing-style-guide"
"/events": "/community"
"/messaging": "/messaging/sms/overview"
"/messaging/sms": "/messaging/sms/overview"
"/messaging/us-short-codes": "/messaging/us-short-codes/overview"
"/messaging/conversion-api": "/messaging/conversion-api/overview"
"/messaging/sns": "/messaging/sns/overview"
"/messaging/sms/building-blocks": "/messaging/sms/building-blocks/send-an-sms"
"/messaging/sms/building-blocks/receive-a-delivery-receipt": "/messaging/sms/guides/delivery-receipts"
"/messaging/sms/guides": "/messaging/sms/overview#sms-api-features"
"/messaging/sms/api-reference": "/api/sms"
"/messaging/tutorials": "/messaging/sms/tutorials"
"/messaging/sms/guides/global-messaging": "/messaging/sms/guides/country-specific-features"
"/messaging/sms/guides/delivery-reciepts": "/messaging/sms/guides/delivery-receipts"
"/messages-and-workflows-apis/messages/api-reference": "/api/messages-and-workflows-apis/messages"
"/messages-and-workflows-apis/workflows/api-reference": "/api/messages-and-workflows-apis/workflows"
"/messages-and-workflows-apis/messages/guides": "/messages-and-workflows-apis/messages/guides/facebook-messenger"
"/messages-and-workflows-apis/workflows/guides": "/messages-and-workflows-apis/workflows/guides/failover"
"/messages-and-workflows-apis/messages/building-blocks": "/messages-and-workflows-apis/messages/building-blocks/send-an-sms-with-messages-api"
"/messages-and-workflows-apis/workflows/building-blocks": "/messages-and-workflows-apis/workflows/building-blocks/send-a-message-with-failover"
"/number-insight": "/number-insight/overview"
"/number-insight/guides": "/number-insight/guides/cnam"
"/number-insight/building-blocks": "/number-insight/building-blocks/number-insight-basic"
"/number-insight/api-reference": "/api/number-insight"
"/redact": "/redact/overview"
"/redact/api-reference": "/api/redact"
"/sip": "/voice/sip"
"/slack": "/community/slack"
"/sms": "/messaging/sms/overview"
"/sms/building-blocks": "/messaging/sms/building-blocks/send-an-sms"
"/sms/guides": "/messaging/sms/guides/us-short-codes/overview"
"/stitch/sdk-documentation/android": "/sdk/stitch/android/"
"/stitch/sdk-documentation/ios": "/sdk/stitch/ios/"
"/stitch/sdk-documentation/javascript": "/sdk/stitch/javascript/"
"/stitch": "/stitch/overview"
"/stitch/api-reference": "/api/stitch"
"/tools/cli": "/tools"
"/verify": "/verify/overview"
"/verify/api-reference": "/api/verify"
"/verify/guides": "/verify/guides/verify-a-user"
"/verify/tutorial": "/verify/tutorials/passwordless-authentication"
"/verify/building-blocks": "/verify/building-blocks/send-verify-request"
"/voice": "/voice/overview"
"/voice/api-reference": "/voice/voice-api/api-reference"
"/voice/sip": "/voice/sip/overview"
"/voice/overview": "/voice/voice-api/overview"
"/voice/tutorials": "/voice/voice-api/tutorials"
"/voice/building-blocks": "/voice/voice-api/building-blocks/before-you-begin"
"/voice/building-blocks/connect-a-phone-call": "/voice/voice-api/building-blocks/connect-an-inbound-call"
"/voice/building-blocks/receive-a-phone-call": "/voice/voice-api/building-blocks/receive-an-inbound-call"
"/voice/guides": "/voice/voice-api/guides/call-flow"
"/voice/guides/sip": "/voice/sip"
"/voice/guides/voice-app-components": "/voice/voice-api/guides/voice-app-components"
"/voice/guides/connect-two-users": "/voice/voice-api/guides/connect-two-users"
"/voice/guides/connecting-voice-calls-to-amazon-lex-bots": "/voice/voice-api/guides/connecting-voice-calls-to-amazon-lex-bots"
"/voice/guides/create-conferences": "/voice/voice-api/guides/create-conferences"
"/voice/guides/handle-call-status": "/voice/voice-api/guides/handle-call-status"
"/voice/guides/inbound-calls": "/voice/voice-api/guides/inbound-calls"
"/voice/guides/interactive-voice-response": "/voice/voice-api/guides/interactive-voice-response"
"/voice/guides/ncco": "/voice/voice-api/guides/ncco"
"/voice/guides/outbound-calls": "/voice/voice-api/guides/outbound-calls"
"/voice/guides/record-calls-and-conversations": "/voice/voice-api/guides/record-calls-and-conversations"
"/voice/guides/call-a-websocket": "/voice/voice-api/guides/call-a-websocket"
"/voice/guides/ncco-reference": "/voice/voice-api/ncco-reference"
"/voice/voice-api/websockets": "/voice/voice-api/guides/websockets"
"/voice/voice-api/api-reference": "/api/voice"
"/voice/voice-api/guides/outbound-calls": "/voice/voice-api/building-blocks/make-an-outbound-call"
"/voice/voice-api/guides/record-calls-and-conversations": "/voice/voice-api/guides/recording"
"/voice/voice-api/guides/connect-two-users": "/voice/voice-api/building-blocks/connect-an-inbound-call"
"/voice/voice-api/guides/create-conferences": "/voice/voice-api/building-blocks/connect-callers-into-a-conference"
"/voice/voice-api/guides/call-a-websocket": "/voice/voice-api/guides/websockets"
"/voice/voice-api/guides/handle-call-status": "/voice/voice-api/guides/call-flow"
"/voice/voice-api/guides/interactive-voice-response": "/voice/voice-api/building-blocks/handle-user-input-with-dtmf"
"/voice/voice-api/guides/inbound-calls": "/voice/voice-api/building-blocks/connect-an-inbound-call"
"/voice/voice-api/guides/voice-app-components": "/voice/voice-api/guides/legs-conversations"
"/voice/voice-api/guides/ssml": "/voice/voice-api/guides/text-to-speech#ssml"
"/voice/voice-api/guides/connecting-voice-calls-to-amazon-lex-bots": "/voice/voice-api/guides/lex-connector"
"/stitch/in-app-messaging/guides/1-simple-conversation/javascript": "/stitch/in-app-messaging/guides/simple-conversation/javascript"
"/stitch/in-app-messaging/guides/1-simple-conversation/android": "/stitch/in-app-messaging/guides/simple-conversation/android"
"/stitch/in-app-messaging/guides/1-simple-conversation/ios": "/stitch/in-app-messaging/guides/simple-conversation/ios"
"/stitch/in-app-messaging/guides/1-simple-conversation": "/stitch/in-app-messaging/guides/simple-conversation"
"/stitch/in-app-messaging/guides/2-inviting-members/javascript": "/stitch/in-app-messaging/guides/inviting-members/javascript"
"/stitch/in-app-messaging/guides/2-inviting-members/android": "/stitch/in-app-messaging/guides/inviting-members/android"
"/stitch/in-app-messaging/guides/2-inviting-members/ios": "/stitch/in-app-messaging/guides/inviting-members/ios"
"/stitch/in-app-messaging/guides/2-inviting-members": "/stitch/in-app-messaging/guides/inviting-members"
"/stitch/in-app-messaging/guides/3-utilizing-events/javascript": "/stitch/in-app-messaging/guides/utilizing-events/javascript"
"/stitch/in-app-messaging/guides/3-utilizing-events/android": "/stitch/in-app-messaging/guides/utilizing-events/android"
"/stitch/in-app-messaging/guides/3-utilizing-events/ios": "/stitch/in-app-messaging/guides/utilizing-events/ios"
"/stitch/in-app-messaging/guides/3-utilizing-events": "/stitch/in-app-messaging/guides/utilizing-events"
"/stitch/in-app-voice/guides/1-enable-audio/javascript": "/stitch/in-app-voice/guides/enable-audio/javascript"
"/stitch/in-app-voice/guides/1-enable-audio/android": "/stitch/in-app-voice/guides/enable-audio/android"
"/stitch/in-app-voice/guides/1-enable-audio/ios": "/stitch/in-app-voice/guides/enable-audio/ios"
"/stitch/in-app-voice/guides/1-enable-audio": "/stitch/in-app-voice/guides/enable-audio"
"/stitch/in-app-voice/guides/2-calling-users/javascript": "/stitch/in-app-voice/guides/calling-users/javascript"
"/stitch/in-app-voice/guides/2-calling-users/android": "/stitch/in-app-voice/guides/calling-users/android"
"/stitch/in-app-voice/guides/2-calling-users/ios": "/stitch/in-app-voice/guides/calling-users/ios"
"/stitch/in-app-voice/guides/2-calling-users": "/stitch/in-app-voice/guides/calling-users"
"/stitch/in-app-voice/guides/3-outbound-pstn/javascript": "/stitch/in-app-voice/guides/outbound-pstn/javascript"
"/stitch/in-app-voice/guides/3-outbound-pstn/android": "/stitch/in-app-voice/guides/outbound-pstn/android"
"/stitch/in-app-voice/guides/3-outbound-pstn/ios": "/stitch/in-app-voice/guides/outbound-pstn/ios"
"/stitch/in-app-voice/guides/3-outbound-pstn": "/stitch/in-app-voice/guides/outbound-pstn"
"/stitch/in-app-video/guides/1-enable-video/javascript": "/stitch/in-app-video/guides/enable-video/javascript"
"/stitch/in-app-video/guides/1-enable-video": "/stitch/in-app-video/guides/enable-video"
"/stitch/in-app-video/guides/2-enable-screenshare/javascript": "/stitch/in-app-video/guides/enable-screenshare/javascript"
"/stitch/in-app-video/guides/2-enable-screenshare": "/stitch/in-app-video/guides/enable-screenshare"
"/sdk/stitch/ios": "/sdk/stitch/ios/"
