# Nexmo repos
# ===========
#
# Used by code examples.
#
# Basic Usage
# -----------
#
# $ bundle exec rake repos:pull
#
# Changes made should be committed into this repo so
# they can be reviewed alongside pull-requests
#
# Developing Locally
# ------------------
#
# Uncomment the path and point it to your local
# working copy of the repo. Running the script
# create a symlink to that directory in place.
#
# Once you are happy with the changes push your
# working repo branch up and comment out the path
# referencing it on GitHub and rerun the command.
#

nexmo-community/nexmo-ruby-quickstart:
  repo: nexmo-community/nexmo-ruby-quickstart
  # path: ../nexmo-ruby-quickstart
nexmo-community/nexmo-node-quickstart:
  repo: nexmo-community/nexmo-node-quickstart
  # path: ../nexmo-node-quickstart
nexmo-community/nexmo-php-quickstart:
  repo: nexmo-community/nexmo-php-quickstart
  # path: ../nexmo-php-quickstart
nexmo-community/nexmo-dotnet-quickstart:
  branch: ASPNET
  repo: nexmo-community/nexmo-dotnet-quickstart
  # path: ../nexmo-dotnet-quickstart
nexmo-community/nexmo-java-quickstart:
  repo: nexmo-community/nexmo-java-quickstart
  # path: ../nexmo-java-quickstart
nexmo-community/nexmo-python-quickstart:
  repo: nexmo-community/nexmo-python-quickstart
  # path: ../nexmo-python-quickstart
nexmo/conversation-docs:
  repo: nexmo/conversation-docs
nexmo/curl-building-blocks:
  repo: nexmo/curl-building-blocks
