current:
  - name: 'Adam Culp'
    email: 'adam.culp@vonage.com'
    role: 'Developer Advocate'
    twitter: 'adamculp'
  - name: 'Alex Lakatos'
    email: 'alex.lakatos@vonage.com'
    twitter: 'lakatos88'  
  - name: 'Amanda Folson'
    email: 'amanda.folson@vonage.com'
    role: 'Developer Relations Manager'
    twitter: 'AmbassadorAwsum'
  - name: 'Chen Hui Jing'
    email: 'huijing.chen@vonage.com'
    twitter: 'hj_chen'
  - name: 'Kelly Andrews'
    email: 'kelly.andrews@vonage.com'
    twitter: 'kellyjandrews'
  - name: 'Lorna Mitchell'
    email: 'lorna.mitchell@vonage.com'
    twitter: 'lornajane'
  - name: 'Martyn Davies'
    email: 'martyn.davies@vonage.com'
    twitter: 'martynd'
    role: 'Developer Relations Manager'
  - name: 'Michael Heap'
    email: 'michael.heap@vonage.com'
    twitter: 'mheap'
    role: 'Developer Relations Manager'
  - name: 'Olia Dukova'
    email: 'olia.dukova@nexmo.com'
    twitter: 'oliadukova'
    role: 'Community Management Lead'
  - name: 'Phil Leggetter'
    email: 'phil.leggetter@vonage.com'
    role: 'Director of Developer Relations'
    twitter: 'leggetter'
  - name: 'Tony Bedford'
    email: 'tony.bedford@vonage.com'
    role: 'Technical Writer'
  - name: 'Myrsini Koukiasa'
    email: 'myrsini.koukiasa@vonage.com'
    twitter: 'myrsiningos'
    role: 'Senior Community Manager'
  - name: 'Garann Means'
    email: 'garann.means@vonage.com'
    role: 'Developer Advocate'
  - name: 'Ben Greenberg'
    email: 'ben.greenberg@vonage.com'
    twitter: 'rabbigreenberg'
    role: 'Developer Advocate'
  - name: 'Paul Ardeleanu'
    email: 'paul.ardeleanu@vonage.com'
    twitter: 'pardel'
    role: 'Developer Advocate'
  - name: 'Luke Oliff'
    email: 'luke.oliff@vonage.com'
    twitter: 'mroliff'
    role: 'Developer Advocate'
  - name: 'Fabian Rodriguez'
    email: 'fabian.rodriguez@vonage.com'
    twitter: 'fabianrbz'
    role: 'Nexmo Developer Tech Lead'
  - name: 'Lauren Lee'
    email: 'lauren.lee@vonage.com'
    twitter: 'lolocoding'
    role: 'Developer Educator'
  - name: 'Laura Czajkowski'
    email: 'laura.czajkowski@vonage.com'
    twitter: 'Czajkowski'
    role: 'Developer Relations Manager'
  - name: 'Bethany Loft'
    email: 'bethany.loft@vonage.com'
    twitter: 'bb_loft'
    role: 'Junior Community Event Manager'
  - name: 'Steve Lorello'
    email: 'steve.lorello@vonage.com'
    twitter: 'slorello'
    role: 'Developer Advocate'
  - name: 'Chris Tankersley'
    email: 'chris.tankersley@vonage.com'
    twitter: 'dragonmantank'
    role: 'Developer Advocate'
  - name: 'Dwane Hemmings'
    email: 'dwane.hemmings@vonage.com'
    twitter: 'dwaneio'
    role: 'Developer Advocate'
  - name: 'Michael Jolley'
    email: 'michael.jolley@vonage.com'
    twitter: 'michaeljolley'
    role: 'Developer Advocate'
  - name: 'Nick Iati'
    email: 'nick.iati@vonage.com'
    role: 'Technical Writer'
  - name: 'Kevin Lewis'
    email: 'kevin.lewis@vonage.com'
    role: 'Developer Advocate'