- name: 'Adam Butler'
  email: 'adam.butler@vonage.com'
  role: 'Nexmo Developer Technical Lead'
  twitter: 'labfoo'
- name: 'Tom Morris'
  email: 'tom.morris@vonage.com'
  role: 'Technical Writer'
  twitter: 'tommorris'
- name: 'Phil Leggetter'
  email: 'phil.leggetter@vonage.com'
  role: 'Director of Developer Relations'
  twitter: 'leggetter'
- name: 'Aaron Bassett'
  email: 'aaron.bassett@vonage.com'
  twitter: 'aaronbassett'
- name: 'Sam Machin'
  email: 'sam.machin@nexmo.com'
  twitter: 'sammachin'
- name: 'Amanda Folson'
  email: 'amanda.folson@vonage.com'
  role: 'Developer Relations Manager'
  twitter: 'AmbassadorAwsum'
- name: 'Alex Lakatos'
  email: 'alex.lakatos@vonage.com'
  twitter: 'lakatos88'
- name: 'Rabeb Othmani'
  email: 'rabeb.othmani@vonage.com'
  twitter: 'Rabeb_Othmani'
- name: 'Olia Dukova'
  email: 'olia.dukova@vonage.com'
  twitter: 'oliadukova'
  role: 'Community Manager'
- name: 'Michael Heap'
  email: 'michael.heap@vonage.com'
  twitter: 'mheap'
- name: 'Chris Guzman'
  email: 'chris.guzman@vonage.com'
  twitter: 'speaktochris'
- name: 'Mark Smith'
  email: 'mark.smith@nexmo.com'
  twitter: 'judy2k'
- name: 'Eric Giannini'
  email: 'eric.giannini@vonage.com'
  twitter: 'eric_giannini'
