current:
  - name: 'Aaron Bassett'
    email: 'aaron.bassett@vonage.com'
    twitter: 'aaronbassett'
  - name: 'Alex Lakatos'
    email: 'alex.lakatos@vonage.com'
    twitter: 'lakatos88'  
  - name: 'Amanda Folson'
    email: 'amanda.folson@vonage.com'
    role: 'Developer Relations Manager'
    twitter: 'AmbassadorAwsum'
  - name: 'Britt Barak'
    email: 'britt.barak@vonage.com'
    twitter: 'brittBarak'
  - name: 'Chen Hui Jing'
    email: 'huijing.chen@vonage.com'
    twitter: 'hj_chen'
  - name: 'Kelly Andrews'
    email: 'kelly.andrews@vonage.com'
    twitter: 'kellyjandrews'
  - name: 'Lorna Mitchell'
    email: 'lorna.mitchell@vonage.com'
    twitter: 'lornajane'
  - name: 'Mark Smith'
    email: 'mark.smith@nexmo.com'
    twitter: 'judy2k'  
  - name: 'Martyn Davies'
    email: 'martyn.davies@vonage.com'
    twitter: 'martynd'
    role: 'Developer Relations Manager'
  - name: 'Michael Heap'
    email: 'michael.heap@vonage.com'
    twitter: 'mheap'      
    role: 'Developer Relations Manager'
  - name: 'Olia Dukova'
    email: 'olia.dukova@nexmo.com'
    twitter: 'oliadukova'
    role: 'Community Management Lead'
  - name: 'Phil Leggetter'
    email: 'phil.leggetter@vonage.com'
    role: 'Director of Developer Relations'
    twitter: 'leggetter'
  - name: 'Rabeb Othmani'
    email: 'rabeb.othmani@vonage.com'
    twitter: 'Rabeb_Othmani'
  - name: 'Sam Machin'
    email: 'sam.machin@nexmo.com'
    twitter: 'sammachin'
  - name: 'Steve Crow'
    email: 'steve.crow@vonage.com'
    twitter: 'cr0wst'
  - name: 'Tony Bedford'
    email: 'tony.bedford@vonage.com'
    role: 'Technical Writer'
  - name: 'Myrsini Koukiasa'
    email: 'myrsini.koukiasa@vonage.com'
    twitter: 'myrsiningos'
    role: 'Senior Community Manager'
  - name: 'Mark Lewin'
    email: 'mark.lewin@vonage.com'
    twitter: 'devtechwriter'
    role: 'Technical Writer'
  - name: 'Manik Sachdeva'
    email: 'manik.sachdeva@vonage.com'
    twitter: 'maniksach'
    role: 'Developer Advocate'
  - name: 'Garann Means'
    email: 'garann.means@vonage.com'
    role: 'Developer Advocate'
  - name: 'Ben Greenberg'
    email: 'ben.greenberg@vonage.com'
    twitter: 'rabbigreenberg'
    role: 'Developer Advocate'
  - name: 'Paul Ardeleanu'
    email: 'paul.ardeleanu@vonage.com'
    twitter: 'pardel'
    role: 'Developer Advocate'
  - name: 'Luke Oliff'
    email: 'luke.oliff@vonage.com'
    twitter: 'mroliff'
    role: 'Developer Advocate'
  - name: 'Fabian Rodriguez'
    email: 'fabian.rodriguez@vonage.com'
    twitter: 'fabianrbz'
    role: 'Nexmo Developer Tech Lead'
alumni:
  - name: 'Adam Butler'
    email: 'adam.butler@vonage.com'
    role: 'Nexmo Developer Technical Lead'
    twitter: 'labfoo'
  - name: 'Tom Morris'
    email: 'tom.morris@vonage.com'
    role: 'Technical Writer'
    twitter: 'tommorris'
  - name: 'Chris Guzman'
    email: 'chris.guzman@vonage.com'
    twitter: 'speaktochris'
