title: "Build an app with accessibility in mind using the Nexmo Voice API and win some great prizes!"

page:
  - row:
    - column:
      - type: html
        html:
          content: '<img src="/assets/images/hacktheburgh2019.png" />'

  - row:
    - column:
        - type: line_divider
  
  - row:
    - column:
      - type: header
        header:
          title:
            text: "Nexmo @ Hack The Burgh 2019"
            align: center
          subtitle:
            text: "Nexmo is sponsoring [Hack The Burgh](https://2019.hacktheburgh.com/) 2019. Use one or more of our APIs in your hack to have a chance of winning some great prizes."
            align: center
          icon:
            name: "icon-star"
            color: "yellow"

  - row:
    - column:
      - type: action_button
        action_button:
          text: "Sign-up For Free"
          url: "https://dashboard.nexmo.com/sign-up?utm_source=nexmo-developer&utm_medium=hacktheburgh2019&utm_campaign=landing"
          center_button: true
          type: primary
          large: true
    - column:
      - type: action_button
        action_button:
          text: "View Nexmo docs"
          url: "/"
          center_button: true
          type: primary
          large: true

  - row:
    - column:
        - type: line_divider

  - row:
    - column:
      - type: structured_text
        structured_text:
          header: "Nexmo Challenge"
          icon:
            name: "icon-laptop"
            color: blue
          text:
          - content: Build an accessible voice application using the [Nexmo Voice API](/voice/voice-api/overview). The Voice API supports the ability to get a raw stream of audio from a phone call or conference over WebSocket.
            type: large
          - content: Use this and other features from the Voice API to make a feature of your hack more accessible.
            type: large

    - column:
      - type: structured_text
        structured_text:
          header: "Mini Challenge"
          icon:
            name: "icon-mobile"
            color: blue
          text:
          - content: A mini challenge with prizes is also running. Send us a text message using the [Nexmo Messages API](/messages/overview).
            type: large
          - content: Send **+447508741510** a text message and then come and see us, show us your code and then get a prize. It's that simple. With 10 prizes to give away we'll give out prizes on a first come first served basis.
            type: large

    - column:
      - type: structured_text
        structured_text:
          header: "Rules & Judging"
          icon:
            name: "icon-books"
            color: blue
          text:
          - content: For the main challenge; You must use the [Nexmo Voice API](/voice/voice-api/overview). Hacks will be judged on **accessibility**, **presentation**, and the **use of the Nexmo Voice API**.
            type: large
          - content: For the mini challenge; You must use the [Nexmo Messages API](/messages/overview). Hacks will be judged on **use of the Nexmo Messages API**.
            type: large

    - column:
      - type: structured_text
        structured_text:
          header: "The Prizes"
          icon:
            name: "icon-thumbs-up"
            color: blue
          text:
          - content: The grand prize for the Nexmo Challenge winners is a set of four [Nanoleaf Rhythm Kits](https://nanoleaf.me/en-gb/consumer-led-lighting/products/smarter-series/nanoleaf-light-panels-smarter-kit/).
            type: large
          - content: The prizes for the mini challenge are [BBC micro:bit](https://microbit.org/) and [Pixl.js](https://shop.espruino.com/pixljs).
            type: large

  - row:
    - column:
        - type: line_divider

  - row:
    - column:
      - type: header
        header:
          title:
            text: "Voice API"
            align: center
          subtitle:
            text: "Check out our Voice API resources."
            align: center
          icon:
            name: "icon-phone"
            color: "green"
      - type: action_button
        action_button:
          text: "Get Started with Nexmo Voice API"
          url: "/voice/voice-api/overview"
          center_button: true
          type: quaternary
          large: true
    - column:
      - type: header
        header:
          title:
            text: "Messages API"
            align: center
          subtitle:
            text: "Check out our Messages API resources."
            align: center
          icon:
            name: "icon-chat"
            color: "blue-dark"
      - type: action_button
        action_button:
          text: "Get Started with Nexmo Messages API"
          url: "/messages/overview"
          center_button: true
          type: secondary
          large: true
    - column:
      - type: header
        header:
          title:
            text: "In-App Voice"
            align: center
          subtitle:
            text: "Check out our In-App Voice resources."
            align: center
          icon:
            name: "icon-volume"
            color: "green"
      - type: action_button
        action_button:
          text: "Get Started with Nexmo In-App Voice"
          url: "/voice-onboarding"
          center_button: true
          type: quaternary
          large: true

  - row:
    - column:
        - type: line_divider

  - row:
    - column:
      - type: section_header
        section_header:
          title: "Handy links and further reading"
          icon:
            name: "icon-pin-2"
            color: "blue-dark"

  - row:
    - column:
      - type: text
        text:
          content: >
            <div class="Vlt-callout Vlt-callout--warning">
            	<i></i>
            	<div class="Vlt-callout__content">
                <h4>Can't find what you're looking for?</h4>
                Come and say hello at the Nexmo booth or find us on the Nexmo channel of the Hack the Burgh slack workspace.
            	</div>
            </div>
  - row:
    - column:
      - type: unordered_list
        unordered_list:
            bullet_shape: simple
            list:
              - item: "[Voice Applications: Before You Begin](/voice/voice-api/code-snippets/before-you-begin)"
              - item: "[Nexmo Call Control Objects (NCCOs)](/voice/voice-api/guides/ncco)"
              - item: "[Interactive Voice Response](/tutorials/interactive-voice-response)"
              - item: "[Connecting Voice Calls to Amazon Lex Bots](/voice/voice-api/guides/lex-connector)"
              - item: "[Receive a Phone Call with Voice API and Swift](https://www.nexmo.com/blog/2019/02/07/receive-call-swift-dr/)"
              - item: "[Forward a Call Via Voice Proxy With Koa.js](https://www.nexmo.com/blog/2019/02/05/forward-call-with-koa-js-dr/)"
    - column:
      - type: unordered_list
        unordered_list:
            bullet_shape: simple
            list:
              - item: "[IBM Watson Speech to Text](/extend/ibm-watson-speech-to-text)"
              - item: "[Microsoft Azure Speech To Text](/extend/azure-speech-to-text)"
              - item: "[Google Cloud Speech Transcription](/extend/google-transcription)"
              - item: "[IBM Watson SMS Sentiment Analysis](/extend/ibm-watson-sms-sentiment-analysis)"
              - item: "[Build a Family Hotline with the Nexmo Voice API!](https://www.nexmo.com/blog/2018/11/20/build-a-family-hotline-dr/)"
              - item: "[Build Watson-enhanced Voice Agents on IBM Cloud with Nexmo](https://www.nexmo.com/blog/2019/02/25/build-watson-enhanced-voice-agents-on-ibm-cloud-with-nexmo/)"
