title: "Nexmo loves PHP! Use our SDKs or make the API calls yourself to integrate with our calling, messaging and mobile platforms"

rows:
  - columns:
    - entries:
      - type: header
        header:
          title:
            text: "Nexmo @ PHP UK 2019"
            align: center
          subtitle:
            text: "Hello, PHPeople! We love catching up with you at events, and we've put together some resources that we hope you find useful."
            align: center
          icon:
            name: "icon-star"
            color: "yellow"
      - type: action_button
        action_button:
          text: "Sign Up For Free"
          url: "https://dashboard.nexmo.com/sign-up?utm_source=nexmo-developer&utm_medium=phpuk19&utm_campaign=landing"
          center_button: true
  - columns:
    - entries:
        - type: line_divider


  - columns:
    - entries:
        - type: header
          header:
            title:
              text: "Nexmo ❤️ PHP"
              align: center
            icon:
              name: "icon-code"
              color: "blue-dark"
        - type: text
          text:
            content: "At Nexmo, we love PHP - it's one of our most-used and most-loved languages by customers and Developer Advocates alike. Start your Nexmo project by installing the Nexmo PHP library:"
        - type: text
          text:
            content: |
              ```
              composer require nexmo/client
              ```
        - type: text
          text:
            content: "Or if Laravel's your thing, we have a prebuilt package that wraps the Nexmo client, reads your config from `.env` and makes it available through the `Nexmo` facade"
        - type: text
          text:
            content: |
              ```
              composer require nexmo/laravel
              ```

    - entries:
        - type: header
          header:
            title:
              text: "Get started by making a call"
              align: center
            icon:
              name: "icon-call"
              color: "blue-dark"
        - type: text
          text:
            content: |
              ```php
              $call = $client->calls()->create([
                  'to' => [[
                      'type' => 'phone',
                      'number' => TO_NUMBER
                  ]],
                  'from' => [
                      'type' => 'phone',
                      'number' => NEXMO_NUMBER
                  ],
                  'answer_url' => ['https://developer.nexmo.com/ncco/tts.json'],
              ]);
              ```

  - columns:
    - entries:
        - type: line_divider

  - columns:
    - entries:
      - type: text
        text:
          content: |
            <span></span>
            <div class="Vlt-callout Vlt-callout--shoutout">
            	<i></i>
            	<div class="Vlt-callout__content">
                **Pro-tip:** Download the OpenAPI spec from our [API reference pages](/api) and import directly into [Postman](https://getpostman.com) as a collection to quickly explore the APIs.
            	</div>
            </div>
            <br />
  - columns:
    - entries:
      - type: call_to_action
        call_to_action:
          title: "Voice"
          subtitle: "Use the Voice API to make and receive phone calls programmatically. You can broadcast messages by phone, respond to incoming calls and route callers according to their input."
          icon: 
            name: "icon-phone"
            color: "green"
          url: "/voice"

    - entries:
      - type: call_to_action
        call_to_action:
          title: "Messages"
          subtitle: "With our Messages API (and its sister Dispatch API) your applications can reach users by the messaging platform they prefer. Message not received? No problem, automatically detect that and try another platform."
          icon: 
            name: "icon-chat"
            color: "purple"
          url: "/messages/overview"

    - entries:
      - type: call_to_action
        call_to_action:
          title: "Verify"
          subtitle: "Ensure that users provide the correct contact details with Verify API. The two-factor authentication (2FA) API reduces fraud and improves contactability for your application's users."
          icon: 
            name: "icon-lock"
            color: "indigo"
          url: "/verify"


  - columns:
    - entries:
        - type: line_divider

  - columns:
    - entries:
      - type: section_header
        section_header:
          title: "Handy PHP-related links and further reading"
          icon:
            name: "icon-pin-2"
            color: "blue-dark"


  - columns:
    - entries:
      - type: text
        text:
          content: >
            <div class="Vlt-callout Vlt-callout--warning">
            	<i></i>
            	<div class="Vlt-callout__content">
                <h4>Can't find what you're looking for?</h4>
                Come and say hello at the Nexmo booth! We'd love to hear what you're having issues with to help you out (and improve the docs at the same time!)
            	</div>
            </div>
  - columns:
    - entries:
      - type: unordered_list
        unordered_list:
            bullet_shape: simple
            list:
              - item: "[Voice Applications: Before you begin](/voice/voice-api/building-blocks/before-you-begin)"
              - item: "[Nexmo Call Control Objects (NCCOs)](/voice/voice-api/guides/ncco)"
              - item: "[Receive an Incoming Call with PHP](https://www.nexmo.com/blog/2018/06/28/receive-an-inbound-voice-call-with-php-dr/)"
              - item: "[Handle Keypad Input (DTMF) with PHP](https://www.nexmo.com/blog/2018/08/10/handle-user-input-with-php-dr/)"
              - item: "[Interactive Voice Response](/tutorials/interactive-voice-response)"
    - entries:
      - type: unordered_list
        unordered_list:
            bullet_shape: simple
            list:
              - item: "[Make an Outbound Call with an NCCO](/voice/voice-api/building-blocks/make-an-outbound-call-with-ncco/php)"
              - item: "[Play Text-to-Speech into a Call](/voice/voice-api/building-blocks/play-text-to-speech-into-a-call/php)"
              - item: "[Record a Call](/voice/voice-api/building-blocks/record-a-call/php)"
              - item: "[Connect Callers into a Conference](/voice/voice-api/building-blocks/connect-callers-into-a-conference/php)"
              - item: "[Transfer a Call](/voice/voice-api/building-blocks/transfer-a-call/php)"
  - columns:
    - entries:
        - type: line_divider
  - columns:
    - entries:
      - type: join_slack
  - columns:
    - entries:
        - type: line_divider
