# Developer Spotlight Landing Page Config

title: "Write for Nexmo"
meta_title: "Developer Spotlight - Teach others, grow as a writer, and help us build the next go-to destination for developers"
container_classes:
  - Vlt-article
page:
  - row:
    - column:
      - type: header
        header:
          title:
            text: "Write for Nexmo"
          subtitle:
            text: "Teach others, grow as a writer, and help us build the next go-to destination for developers in search of [high quality technical content](https://www.nexmo.com/blog/category/developer/) and inspiring development stories."
            type: 'small'
          icon:
            name: "icon-rocket"
            color: blue
      - type: action_button
        action_button:
          text: "Apply Now"
          url: "#submit-your-idea"
    - width: 2
      column:
      - type: html
        html:
          content: '<img src="/assets/images/developer_spotlight.png" />'
  - row:
    - column:
        - type: line_divider
  - row:
    - width: 2
      column:
      - type: section_header
        section_header:
          title: "Examples"
          icon:
            name: "icon-app"
            color: yellow
      - type: linked_image
        linked_image:
          image: "https://www.nexmo.com/wp-content/uploads/2019/10/E_2FA-WordPress_1200x600.jpg"
          url: "https://www.nexmo.com/blog/2019/10/09/adding-2-factor-authentication-to-wordpress-with-nexmo-verify-api-dr"
          alt_text: "Adding 2-Factor Authentication to WordPress with Nexmo Verify API"
      - type: linked_image
        linked_image:
          image: "https://www.nexmo.com/wp-content/uploads/2019/09/E_GitLab-CI-Pipeline_1200x600.jpg"
          url: "https://www.nexmo.com/blog/2019/09/30/sending-gitlab-ci-pipeline-notifications-with-nexmo-messages-dr"
          alt_text: "Sending GitLab CI Pipeline Notifications with Nexmo Messages"
      - type: linked_image
        linked_image:
          image: "https://www.nexmo.com/wp-content/uploads/2019/08/Incident-Reporting_1200x600.jpg"
          url: "https://www.nexmo.com/blog/2019/08/21/incident-reporting-with-pagerduty-and-nexmo-dr"
          alt_text: "Incident Reporting with PagerDuty and Nexmo"
      - type: linked_image
        linked_image:
          image: "https://www.nexmo.com/wp-content/uploads/2019/06/unnamed.jpg"
          url: "https://www.nexmo.com/blog/2019/06/20/creating-a-complex-ivr-system-with-ease-with-xstate-dr"
          alt_text: "Creating a Complex IVR System with Ease with XState"
    - width: 2
      column:
      - type: structured_text
        structured_text:
          header: "What We're Looking For"
          icon:
            name: "icon-search"
            color: blue
          text:
            - content: "We're interested in both technical tutorials and general pieces on programming. Successful submissions will be:"
              type: large
            - content: "**Original.** Literally, we want original work (nothing that has been published elsewhere). And more figuratively, we want to see original thought and interesting points of view we can't find anywhere else."
              type: small
            - content: "**Well-written.** Our standards are high, and we want everything published on our blog to meet those standards. That said, you don't have to be a professional writer to submit! If the post is original, helpful and interesting, our editorial team is happy to work with you to get it publication ready."
              type: small
      - type: structured_text
        structured_text:
          header: "What's in it for You?"
          icon:
            name: "icon-user"
            color: blue
          text:
            - content: "We pay $400 USD per post. Your tutorial will be published on our blog, and may be shared in our newsletter or showcased as part of our \"Tutorial Tuesday\" weekly feature."
              type: large
            - content: "We make every effort to amplify the reach of each and every blog post on our site, and yours will be no exception; you'll have the Nexmo marketing and social media teams behind you getting the word out about your work. Your success is our success."
              type: small
            - content: "And Now Introducing:  [Spotlight for Donations]( https://www.nexmo.com/blog/2019/09/04/nexmo-launches-spotlight-for-donations-program-dr)"
              type: large
            - content: "Authors can now choose to pay it forward and donate their $400 to a charity making a difference in the technology industry."
              type: small
      - type: structured_text
        structured_text:
          header: "The Process"
          icon:
            name: "icon-gear"
            color: blue
          text:
          - content: "When we receive your submission, our editorial team will evaluate it to see if it's a good fit for the Nexmo blog."
            type: large
          - content: "Submission is not a guarantee that your work will be published; we reserve the right to decline submissions that aren't right for our platform. But we really want to help you get published so if you take the time to submit, we will review your work and provide feedback. Our goal is simple: we want to see what you're doing with Nexmo's products, and we want you to share your story with the community."
            type: small
          - content: "We'll be in touch to let you know if we want to publish your post and tell you what the next steps are."
            type: small
      - type: structured_text
        structured_text:
          header: "Who Owns Your Work?"
          icon:
            name: "icon-merge"
            color: blue
          text:
          - content: "You do! You grant Nexmo an unlimited license to publish and promote your post, but you retain full ownership."
            type: large
          - content: "This means you are free to re-publish elsewhere (on your own Medium page, for example). All we require is that you add a `rel=canonical` tag to your post wherever possible, naming the original post at Nexmo the canonical URL."
            type: small
      - type: submit_your_idea_form
        submit_your_idea_form:
          header: "Submit Your Idea"
          icon:
            name: "icon-envelope"
            color: blue
