name: PR Edited
on:
  pull_request:
    types: [opened, synchronize, labeled]
jobs:
  create-review-app:
    runs-on: ubuntu-latest
    steps:
    - name: Create Review App
      uses: mheap/github-action-pr-heroku-review-app@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HEROKU_PIPELINE_ID: ${{ secrets.HEROKU_PIPELINE_ID }}
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
